### PR TITLE
Added CoffeeScript support.

### PR DESCRIPTION
**Pull request by Crenshinibon**
Hope that is ok. Tested it locally and works fine. I made no tests though.

### CODE REVIEW

**Comment by arunoda** [comment]
Great. Yes currently there is no tests written for testing laika features. (I'm still searching a way to do it)
Only the core is tested.
We'll add tests later. I'll work on the merge.

**Comment by arunoda** [comment]
I'm having trouble with how to use this.
Can you tell me how I can use some coffee files with this? an example (think I've nothing installed related to coffee)

**Comment by Crenshinibon** [comment]
I forked your example and switched it to CoffeeScript. You need the 'coffee-script' package being available. Installed through npm. I think globally. You might as well include it into the laika dependencies. Want me to issue a pull request for the latter?

Tested the latter right now. Previously I did it with coffee globally installed.

Here is the example project:
https://github.com/Crenshinibon/hello-laika

You run the tests with:

```
laika --compilers coffee:coffee-script
```

**Comment by arunoda** [comment]
I've refactored a bit into my style of coding. hope you wouldn't mind it :)
Published as `0.2.12`

**Comment by Crenshinibon** [comment]
No I don't mind. JavaScript is just a compilation target for me, and I'm not very comfy in writing it.

I thought about merging the extraction of valid extensions and compilers in one step, too. The mocha people did it that way. You might want to have a look.

**Comment by arunoda** [comment]
Yes. I know. I prefer readability over less line numbers.

On Fri, Jul 12, 2013 at 1:08 PM, Dirk Porsche notifications@github.comwrote:

> No I don't mind.
> 
> I thought about merging the extraction of valid extensions and compilers
> in one step, too. The mocha people did it that way. You might want to have
> a look.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/pull/32#issuecomment-20862637
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Pull request merged**
