### PR TITLE
Fixtures and remote Collections in an 'advanced' example

### PR DESCRIPTION
**Pull request by zvictor**
I hope it can be part of Laika soon.

### CODE REVIEW

**Comment by zvictor** [comment]
Oh my gosh! You are really fast!
Is @arunoda a bot? =p

**Comment by arunoda** [comment]
Victor this is great. shows how to use other node modules. kudos.
I would also like to have this as a complete diff repo. So I can include this into the docs directly

Can you create a separate repo on this?

**Comment by zvictor** [comment]
Yes, I can.

So, do you want me to create a new repo only for this 'advanced' example?

**Comment by arunoda** [comment]
yes. exactly.
If possible add it to this page too:
http://arunoda.github.io/laika/examples.html

On Wed, Jun 12, 2013 at 10:45 PM, zVictor notifications@github.com wrote:

> Yes, I can.
> 
> So, do you want me to create a new repo only for this 'advanced' example?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/laika/pull/11#issuecomment-19340586
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by zvictor** [comment]
done. https://github.com/zvictor/laika-extended-example

**Comment by arunoda** [comment]
merged: http://arunoda.github.io/laika/examples.html :)

**Pull request merged**
