### PR TITLE
Apply settings to the first application launch

### PR DESCRIPTION
**Pull request by eluck**
When an application under tests was launched first, it didn't recieve settings which were passed as parameter to laika.
Why settings are passed via --settings parameter instead of the environment variable? Because in the latter case settings were applied to an application with a significant delay after start.

[Review on Reviewable](https://reviewable.io/reviews/arunoda/laika/149)

### CODE REVIEW

**Comment by apendua** [comment]
@eluck Good catch!

**Comment by eluck** [comment]
@apendua Thanks! Is Laika currently supported? I see a lot of your unmerged pull requests.

**Comment by apendua** [comment]
@eluck Good question! I can see that almost half of those PRs are mine :)

Anyway, we try to do our best to keep laika compatible with the latest meteor versions, but we don't really develop new features. This is mainly because it's very hard to ensure backward compatibility.

Also, it's very likely that in the nearest future Gagarin will replace laika:
https://github.com/anticoders/gagarin

**Comment by eluck** [comment]
@apendua Great stuff! I try using Laika as a performance tests runner. Running tests in a clean environment is essential for that. So I'd like the project to be developed and supported no matter how it is named. BTW cool picture :)

**Pull request closed without merging**
